### ISSUE TITLE
Installation section

### ISSUE THREAD

**Issue by simonmeusel** [MrAdamBoyd/DownTube#1]
I've been trying to install this App to my IPad via XCode but got some errors (missing dependencies). It would be nice if you add a **installation section** into the readme or as a wiki page :)

**Comment by MrAdamBoyd** [comment]
I just added an installation section @simonmeusel. Let me know if that doesn't help solve your issues!

**Comment by simonmeusel** [comment]
Thank you for the quick answer. I'm getting some errors tho:

# 1. Bundle Identifier
When clicking on Fix Issue:
`An App ID with Identifier 'com.adam.DownTube.DownTubeShareExtension' is not available. Please enter a different string.`

So i changed the bundle id to de.simonmeusel.DownTube  and de.simonmeusel.DownTube.DownTubeShareExtension

# 2. When running:

```
Failed to code sign "DownTubeShareExtension".

None of the valid provisioning profiles allowed the specified entitlements: com.apple.security.application-groups.

Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles.
```

So i clicked on Fix Issue:

```
Communication with Apple failed

Your account does not have sufficient permissions to modify containers.
```

I tried to just put a plain app to my iphone and it worked.
I'm **not** having an Apple developer account for ~100 $ / year, so maybe that's the cause.

**Comment by MrAdamBoyd** [comment]
You shouldn't have to have the $100 dev account. Can you try again off of the `installing` branch? I believe I removed the entitlements that were causing the issue.

**Comment by simonmeusel** [comment]
It works!

Thank you for the quick support. Very useful app!
